### ISSUE TITLE
clean argument of upload function not compatible with providing own credentials

### ISSUE THREAD

**Issue by kevinjoyner** [maybelinot/df2gspread#13]
Hi. I think I've worked out a problem I was getting.

If you need to provide your own credentials for uploading a data frame to a gsheet, and you also set the clean parameter on the upload function to True, then you'll get an error, e.g.

oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', '/home/user/.gdrive_private', 'No such file or directory', 2)

... and I think this is because the clean_worksheet function calls upload without providing the credentials argument.

But, you know, I'm not sure if the clean argument is needed anyway, is it? It seems as though an upload replaces the whole gsheet tab anyway (and I think I've seen this mentioned somewhere in the documentation).

Thanks

Kev

**Comment by maybelinot** [comment]
Hi, @kevinjoyner, thanks for providing detailed information about an issue..

Clean argument is needed, because uploading will not clean whole worksheet, it'll only rewrite cells  by the shape of uploaded DataFrame, so uploading of big *df* and then small one will produce *df* with size of big one and changed cells in the shape of small *df*. And I made it optional for possibility of uploading *df* on exact cell in the future
